import tradebotImage from '../../pictures/projects/tradebot.jpg';
import backlogBuddyImage from '../../pictures/projects/backlog-buddy.jpg';
import sonicActionRpgImage from '../../pictures/projects/sonic-action-rpg.png';
import chessNeuralNetworkImage from '../../pictures/projects/chess-neural-network.jpg';
import theCollectiveImage from '../../pictures/projects/the-collective.jpg';
import audioScribeImage from '../../pictures/projects/audioscribe.jpg';
import usfbcAdminPlatformImage from '../../pictures/projects/usfbc-admin-platform.jpg';
import nflAnalyticsDashboardImage from '../../pictures/projects/nfl-analytics-dashboard.jpg';
import linkedinCandidateAnalyticsImage from '../../pictures/projects/linkedin-candidate-analytics.jpg';

export const projects = [
    {
        slug: 'tradebot',
        title: 'Q-Trader',
        subtitle: 'Algorithmic Trading Bot',
        description: 'A Python reinforcement-learning trading bot that studies years of hourly market data and builds a Q-learning "brain" out of technical signals like SMA ratio, Bollinger %B, MACD and RSI, with self-adjusting weights. It includes a full backtesting engine with walk-forward validation, Sharpe ratio and drawdown metrics, a FastAPI control/status API, and email alerting, and runs continuously on a self-hosted server via Docker and systemd.',
        techStack: ['Python', 'FastAPI', 'Docker'],
        githubUrl: 'https://github.com/Smashthehedgehog/tradebot',
        liveUrl: null,
        attribution: null,
        accent: 'blue-red',
        image: tradebotImage,
    },
    {
        slug: 'video-game-backlog-project',
        title: 'Backlog Buddy',
        subtitle: 'Video Game Backlog Tracker',
        description: 'A full-stack app for tracking a personal video-game backlog: an Express/Node API pulls game metadata from IGDB into Supabase on a weekly scheduled sync, and a React, Vite and TypeScript frontend (styled with Tailwind) lets you browse and manage the collection. The monorepo is already structured for a future React Native companion app.',
        techStack: ['React', 'TypeScript', 'Node.js', 'Supabase'],
        githubUrl: 'https://github.com/Smashthehedgehog/video-game-backlog-project',
        liveUrl: null,
        attribution: null,
        accent: 'amber-mint',
        image: backlogBuddyImage,
    },
    {
        slug: 'action-rpg-project',
        title: 'Sonic Action RPG',
        subtitle: '2D Action RPG (Godot)',
        description: 'A 2D action-RPG built in the Godot engine starring a Sonic-the-Hedgehog-style playable character, driven by a custom finite state machine for both the player and enemies. It features spells, battle maps and enemy AI, and was built to learn game-design fundamentals while sharpening object-oriented design skills.',
        techStack: ['Godot', 'C Sharp'],
        githubUrl: 'https://github.com/Smashthehedgehog/Action_RPG_Project',
        liveUrl: null,
        attribution: null,
        accent: 'blue-red',
        image: sonicActionRpgImage,
    },
    {
        slug: 'chess-neural-network',
        title: 'ChessMind',
        subtitle: 'Chess-Move Prediction Neural Network',
        description: 'A chess-move-prediction neural network trained on a Lichess game database using TensorFlow and Keras, paired with a playable pygame chess interface to try it out move by move. The repo includes multiple trained model variants, including a more "aggressive" playstyle model.',
        techStack: ['Python', 'TensorFlow'],
        githubUrl: 'https://github.com/Smashthehedgehog/chess_neural_network',
        liveUrl: null,
        attribution: null,
        accent: 'amber-mint',
        image: chessNeuralNetworkImage,
    },
    {
        slug: 'the-collective',
        title: 'The Collective',
        subtitle: 'Sports Article Publishing Platform',
        description: 'A multi-writer basketball article publishing platform built on Next.js and Payload CMS, with a full editorial workflow (draft, review, publish), rich embeds for YouTube clips, tweets and live stat visuals, reader accounts, and visitor analytics. It ships with a legacy-content importer and cron-driven digest emails. I created the site from the ground up, and my LB and the site owner took it from there',
        techStack: ['Next.js', 'TypeScript', 'Payload CMS'],
        githubUrl: 'https://github.com/Smashthehedgehog/the-collective-test',
        liveUrl: 'https://thehardwoodcollective.com/',
        attribution: null,
        accent: 'blue-red',
        image: theCollectiveImage,
    },
    {
        slug: 'gen-ai-mp3-to-musescore',
        title: 'AudioScribe',
        subtitle: 'Generative-AI Music Transcription (Experimental)',
        description: 'An experimental project exploring whether AI source-separation and transcription models can turn an MP3 into readable sheet music, combining Demucs for stem separation with the MT3 model for note transcription. Still an early-stage workspace with mixed results, kept here as an ongoing exploration.',
        techStack: ['Python'],
        githubUrl: 'https://github.com/Smashthehedgehog/gen-ai-mp3-to-musescore',
        liveUrl: null,
        attribution: null,
        accent: 'amber-mint',
        image: audioScribeImage,
    },
    {
        slug: 'usfbc-admin-platform',
        title: 'USFBC Admin Platform',
        subtitle: 'Nonprofit Survey & Admin App',
        description: 'A full-stack survey and admin platform built for the nonprofit USFBC, with a Flask and SQLite backend for managing users and surveys, and a React and Bootstrap frontend deployed through AWS Amplify. Built with a small team, with a focus on frontend UI/UX components.',
        techStack: ['React', 'Bootstrap', 'Flask'],
        githubUrl: 'https://github.com/Usfbc-admin/app',
        liveUrl: null,
        attribution: 'Team project — built with USFBC',
        accent: 'blue-red',
        image: usfbcAdminPlatformImage,
    },
    {
        slug: 'nfl-analytics-dashboard',
        title: 'NFL Analytics Dashboard',
        subtitle: 'Data Visual Analytics',
        description: 'An interactive NFL play-by-play analytics dashboard built for Georgia Tech\'s Data & Visual Analytics course, with team, player and situational breakdowns, EPA-based visualizations, and a win-probability model comparing Random Forest, linear and gradient-boosting approaches over nflverse data.',
        techStack: ['Python'],
        githubUrl: 'https://github.com/cutamar/cse6242-team079',
        liveUrl: null,
        attribution: 'Team project — Georgia Tech',
        accent: 'amber-mint',
        image: nflAnalyticsDashboardImage,
    },
    {
        slug: 'linkedin-candidate-analytics',
        title: 'Candidate Analytics Dashboard',
        subtitle: 'Recruiting Analytics Dashboard',
        description: 'A responsive, client-side dashboard for filtering, sorting and visualizing recruiting-candidate data exports, built as freelance client work for AutoNateAI. It parses CSV exports in the browser and renders sortable tables and charts, no backend required.',
        techStack: ['JavaScript', 'Bootstrap'],
        githubUrl: 'https://github.com/AutoNateAI/LinkedIn-Candidate-Analytics-And-Finder',
        liveUrl: 'https://autonateai.github.io/LinkedIn-Candidate-Analytics-And-Finder/',
        attribution: 'Client project — AutoNateAI',
        accent: 'blue-red',
        image: linkedinCandidateAnalyticsImage,
    },
];
